# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171001_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teachers_course',
            field=models.CharField(default=datetime.datetime(2017, 10, 3, 9, 40, 8, 414527, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachers_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
