# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171003_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachers_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
