# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20171003_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='executive',
            name='executive_email',
            field=models.EmailField(default=datetime.datetime(2017, 10, 3, 21, 37, 35, 222410, tzinfo=utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executive',
            name='executive_phone',
            field=models.CharField(default=datetime.datetime(2017, 10, 3, 21, 37, 42, 411572, tzinfo=utc), max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_qualification',
            field=models.CharField(choices=[('OND', 'OND'), ('Bsc', 'Bsc'), ('Msc', 'Msc'), ('NCE', 'NCE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachers_qualification',
            field=models.CharField(choices=[('OND', 'OND'), ('Bsc', 'Bsc'), ('Msc', 'Msc'), ('NCE', 'NCE')], max_length=10),
        ),
    ]
