# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_teacher_teachers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 4, 11, 49, 40, 921192, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default=datetime.datetime(2017, 10, 4, 11, 49, 49, 262653, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
