# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171004_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=datetime.datetime(2017, 10, 4, 19, 41, 10, 910021, tzinfo=utc), max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
